### ISSUE TITLE
Idea: Use modules instead of YAML for evals

### ISSUE THREAD

**Issue by crertel** [ash-project/evals#5]
### Is your feature request related to a problem? Please describe.

So, I don't really understand why you'd want YAML definitions for this, especially given the awkward assertion code.

### Describe the solution you'd like

It would make more sense to me to use normal Elixir modules with perhaps a helper `use`. Like, why complicate things?

**Comment by zachdaniel** [comment]
Explained on twitter, copying here as well:

>  Primarily because we want this to be consumable externally. We want it to be a consumption method agnostic tool so that others can use it to other ends (like maybe training their models 🤞 )

If you know my track record you should know I'm *all about* using Elixir modules as a data format 😆. But in this case I personally think that the ability for someone to scrape this data set and use it for something else is just too important.

**Comment by crertel** [comment]
Compare:

```
type: write_code_and_assert
messages:
  - type: user
    text: |
      Write a function called `add` that adds two numbers. Return just the function, not wrapped in a module
eval:
  assert:
    wrap_in_module: true
    assertion: "<%= @module_name %>.add(2, 3) == 5"
```

```
defmodule Evals.Elixir.SimpleAddition do

@behaviour Evals.EvalBehaviour # cleaner, shorter ways to do this exist, possibly a macro to also pull in ExUnit?

def messages, do: [
  {"user", "Write a function called `add` that adds two numbers. Return just the function, not wrapped in a module"}
  ]

  test "generates module with correct add/2 helper" do
    # ExUnit-style asserts here...
  end 
end 
```
